"""Edit promotionpitch & added Interview

Revision ID: 128a789983bf
Revises: b66aac6e8bec
Create Date: 2020-09-23 16:19:03.382118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128a789983bf'
down_revision = 'b66aac6e8bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview')
    # ### end Alembic commands ###
