"""added pickup likes

Revision ID: 4e597f3259d9
Revises: 5196512db1de
Create Date: 2020-09-27 15:30:56.969974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e597f3259d9'
down_revision = '5196512db1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickuplikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pickuplines_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pickuplines_id'], ['pickuplines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickuplikes')
    # ### end Alembic commands ###
